using DSharpPlus.CommandsNext;
using DSharpPlus.CommandsNext.Attributes;

namespace WarzoneDiscordBot.Modules
{
    public class ComplimentModule : BaseCommandModule
    {
        [Command("compliment")]
        [Aliases("c")]
        [Description("Compliments a user")]
        private async Task ComplimentUser(CommandContext context,
        [Description("User that will be complimented")] string user)
        {
            var adjective_one = new string[] {
                "handsome",
                "strapping",
                "sexy",
                "godlike",
                "big-dick",
                "chiseled",
                "cute",
                "beautiful",
                "Affectionate",
                "Agreeable",
                "Amiable",
                "Bright",
                "Charming",
                "Creative",
                "Determined",
                "Energetic",
                "Friendly",
                "Funny",
                "Generous",
                "Imaginative",
                "Polite",
                "Likable",
                "Gregarious",
                "Diplomatic",
                "Sincere",
                "Helpful",
                "Giving",
                "Kind",
                "Hardworking",
                "Diligent",
                "Patient",
                "Dynamic",
                "Loyal",
                "Ample",
                "bountiful",
                "glistening",
                "dazzling",
                "twinkling",
                "lustrous",
                "vivid",
                "vibrant",
                "vivacious",
                "glowing",
                "gleaming",
                "sparkling",
                "shimmering",
                "glimmering",
                "glittering",
                "brilliant",
                "elegant",
                "sleek",
                "alluring",
                "enchanting",
                "ravishing",
                "magnificent",
                "captivating",
                "lovely",
                "glowing",
                };

            var adjective_two = new string[] {
                "high-kd",
                "cracked",
                "insanely good",
                "well rounded",
                "smart",
                "thoughtful",
                "hit it and quit it",
                "poon slaying",
                "ass destroying",
                "wham bamming",
                "brave",
                "self-confident",
                "sensible",
                "sincere",
                "thoughtful",
                "warmhearted",
                "willing",
                "proficient",
                "romantic",
                "powerful",
                "persistent",
                "passionate",
                "loving",
                "faithful",
                "nice",
                "optimistic",
                "plucky",
                "philosophical",
                "humorous",
                "frank",
                "fearless",
                "considerate",
                "courageous",
                "marvelous",
                "capable",
                "accomplished",
                "knowledgeable",
                "adept",
                "expert",
                "engaging",
                "amazing",
                "awesome",
                "blithesome",
                "excellent",
                "fabulous",
                "fantastic",
                "favorable",
                "fortuitous",
                "gorgeous",
                "incredible",
                "unique",
                "mirthful",
                "outstanding",
                "perfect",
                "propitious",
                "remarkable",
                "rousing",
                "spectacular",
                "splendid",
                "stellar",
                "stupendous",
                "super",
                "upbeat",
                "stunning",
                "wondrous",
                };

            var noun = new string[] {
                "nigga",
                "Chad",
                "beast",
                "great guy",
                "loved person",
                "human being",
                "American",
                "non-fag",
                "gentleman",
                "friend",
                "adult",
                "grown ass man",
                "masturbater",
                "king",
                "guy",
                "bro",
                "fella",
                "homie",
                };

            // Build the compliment.
            var rnd = new Random();
            var insult = new string[] {
            adjective_one[rnd.Next(0, adjective_one.Length - 1)],
            adjective_two[rnd.Next(0, adjective_two.Length - 1)],
            noun[rnd.Next(0, noun.Length - 1)] };

            await context.Channel.SendMessageAsync($"{user} is a {insult[0].ToLower()} {insult[1].ToLower()} {insult[2].ToLower()}");
        }
    }
}
