using DSharpPlus.CommandsNext;
using DSharpPlus.CommandsNext.Attributes;

namespace Discord_Botler.Commands
{
    public class InsultCommand : BaseCommandModule
    {


        [Command("insult")]
        [Description("Insults a user")]
        private async Task InsultUser(CommandContext context,
        [Description("User that will be insulted")] string user)
        {
            var adjective_one = new string[] {
                "artless",
                "bawdy",
                "beslubbering",
                "bootless",
                "churlish",
                "cockered",
                "clouted",
                "craven",
                "currish",
                "dankish",
                "dissembling",
                "droning",
                "errant",
                "fawning",
                "fobbing",
                "froward",
                "frothy",
                "gleeking",
                "goatish",
                "gorbellied",
                "impertinent",
                "infectious",
                "jarring",
                "loggerheaded",
                "lumpish",
                "mammering",
                "mangled",
                "mewling",
                "paunchy",
                "pribbling",
                "puking",
                "puny",
                "qualling",
                "rank",
                "reeky",
                "roguish",
                "ruttish",
                "saucy",
                "spleeny",
                "spongy",
                "surly",
                "tottering",
                "unmuzzled",
                "vain",
                "venomed",
                "villainous",
                "warped",
                "wayward",
                "weedy",
                "smarmy",
                "stinky",
                "farty",
                "cheese-toothed",
                "common",
                "boil-dripping",
                "beefy",
                "fart-sniffing",
                "slug-slimed",
                "pinheaded",
                "two-toned",
                "zebra-headed",
                "slime-coated",
                "pimple-farmin",
                "paramecium-brained",
                "empty-headed",
                "malodorous",
                "silly",
                "snotty-faced",
                "vacuous",
                "philistine",
                "loathsome",
                "lousy",
                "blackballing",
                "bleeding",
                "so-called",
                "woody",
                "tinny",
                "festering",
                "yeasty"
                };

            var adjective_two = new string[] {
                "base-court",
                "bat-fowling",
                "beef-witted",
                "beetle-headed",
                "boil-brained",
                "clapper-clawed",
                "clay-brained",
                "common-kissing",
                "crook-pated",
                "dismal-dreaming",
                "dizzy-eyed",
                "doghearted",
                "dread-bolted",
                "earth-vexing",
                "elf-skinned",
                "fat-kidneyed",
                "fen-sucked",
                "flap-mouthed",
                "fly-bitten",
                "folly-fallen",
                "fool-born",
                "full-gorged",
                "guts-griping",
                "half-faced",
                "hasty-witted",
                "hedge-born",
                "hell-hated",
                "idle-headed",
                "ill-breeding",
                "ill-nurtured",
                "knotty-pated",
                "milk-livered",
                "motley-minded",
                "onion-eyed",
                "plume-plucked",
                "pottle-deep",
                "pox-marked",
                "reeling-ripe",
                "rough-hewn",
                "rude-growing",
                "rump-fed",
                "shard-borne",
                "sheep-biting",
                "spur-galled",
                "swag-bellied",
                "tardy-gaited",
                "tickle-brained",
                "toad-spotted",
                "unchin-snouted",
                "contrarian",
                "smelly",
                "toilet-breathed",
                "gregarious",
                "scab-picked",
                "pimple-squeezing",
                "cheesy",
                "mung tongue",
                "camel-cake",
                "lying, crying, spying, prying",
                "elderberry-smelling",
                "coffee-nosed",
                "stupid",
                "non-creative",
                "spotty",
                "hypocrtitical",
                "whining",
                "stinking",
                "purulent",
                "blind",
                "naughty",
                "weather-bitten"
            };

            var noun = new string[] {
                "apple-john",
                "baggage",
                "barnacle",
                "bladder",
                "boar-pig",
                "bugbear",
                "bum-bailey",
                "canker-blossom",
                "clack-dish",
                "clotpole",
                "coxcomb",
                "codpiece",
                "death-token",
                "dewberry",
                "flap-dragon",
                "flax-wench",
                "flirt-gill",
                "foot-licker",
                "fustilarian",
                "giglet",
                "gudgeon",
                "haggard",
                "harpy",
                "hedge-pig",
                "horn-beast",
                "hugger-mugger",
                "joithead",
                "lewdster",
                "lout",
                "maggot-pie",
                "malt-worm",
                "mammet",
                "measle",
                "minnow",
                "miscreant",
                "moldwarp",
                "mumble-news",
                "nut-hook",
                "pigeon-egg",
                "pignut",
                "puttock",
                "pumpion",
                "ratsbane",
                "scut",
                "skainsmate",
                "strumpet",
                "varlot",
                "vassal",
                "whey-face",
                "ass-hat",
                "jerk",
                "ass-captain",
                "ass",
                "pig",
                "dick",
                "butt-burglar",
                "turd-burglar",
                "clack-dish",
                "fart-biscuit",
                "lawyer",
                "fuckwaffle",
                "bubble-butt",
                "fart factory",
                "sack-of-rat-guts-in-cat-vomit",
                "finger bandage",
                "week old maggot burger with everything on it and flies on the side",
                "substitute chemistry teacher",
                "math tutor",
                "prison barber",
                "near-sighted gynecologist",
                "ultra-pig",
                "lewd, crude, rude, bag of pre-chewed food dude",
                "maggot burger",
                "lawyer",
                "animal food trough wiper",
                "hamster",
                "English pig-dog",
                "son of a silly person",
                "heap of parrot droppings",
                "pervert",
                "git",
                "garbage",
                "excrement",
                "Freemason",
                "bignose",
                "bat",
                "private part",
                "chemist",
                "Brewboy",
                "wagtail"
                };

            // Build the insult.
            var rnd = new Random();
            var insult = new string[] {
            adjective_one[rnd.Next(0, adjective_one.Length - 1)],
            adjective_two[rnd.Next(0, adjective_two.Length - 1)],
            noun[rnd.Next(0, noun.Length - 1)] };

            await context.Channel.SendMessageAsync($"{user} is a {insult[0]} {insult[1]} {insult[2]}.");
        }
    }
}
